MODULE := mlkem

CFLAGS += -Wno-sign-compare
CFLAGS += -Wno-unused-parameter

CFLAGS += -O3 -Wall -Wextra -Wpedantic -Werror \
          -Wmissing-prototypes -Wredundant-decls -std=c99 

SRC += src/cbd.c
SRC += src/indcpa.c
SRC += src/kem.c
SRC += src/ntt.c
SRC += src/poly.c
SRC += src/polyvec.c
SRC += src/reduce.c
SRC += src/fips202.c
SRC += src/symmetric-shake.c
SRC += src/verify.c

include $(RIOTBASE)/Makefile.base

